.grid-padding-left--{paddingLeft}:
  title: Page padding left
  type: string
  enum:
    - 2mm
    - 4mm
    - 6mm
    - 8mm
  enumNames:
    - 2mm
    - 4mm
    - 6mm
    - 8mm

.grid-padding-right--{paddingRight}:
  title: Page padding right
  type: string
  enum:
    - 2mm
    - 4mm
    - 6mm
    - 8mm
  enumNames:
    - 2mm
    - 4mm
    - 6mm
    - 8mm

.theme--{theme}:
  title: Theme
  type: array
  uniqueItems: true
  items:
    type: string
    enum:
      - default
      - blue
    enumNames:
      - Default
      - Blue

"[data-map]":
  title: Article types
  type: array
  uniqueItems: true
  items:
    type: string
    enum:
      - article
    enumNames:
      - All
